/**************************************************************************/
/*!
    @file     http_common.h
    @author   hathach

    @section LICENSE

    Software License Agreement (BSD License)

    Copyright (c) 2016, Adafruit Industries (adafruit.com)
    All rights reserved.

    Redistribution and use in source and binary forms, with or without
    modification, are permitted provided that the following conditions are met:
    1. Redistributions of source code must retain the above copyright
    notice, this list of conditions and the following disclaimer.
    2. Redistributions in binary form must reproduce the above copyright
    notice, this list of conditions and the following disclaimer in the
    documentation and/or other materials provided with the distribution.
    3. Neither the name of the copyright holders nor the
    names of its contributors may be used to endorse or promote products
    derived from this software without specific prior written permission.

    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ''AS IS'' AND ANY
    EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
    WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
    DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY
    DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
    (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
    ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
    (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
    SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
/**************************************************************************/

#ifndef _HTTP_COMMON_H_
#define _HTTP_COMMON_H_

#include <Arduino.h>

#define HTTP_METHOD_GET         "GET"
#define HTTP_METHOD_POST        "POST"
#define HTTP_VERSION            "HTTP/1.1"

#define HTTP_HEADER_URLENCODING "application/x-www-form-urlencoded"

typedef enum
{
  HTTP_STATUS_CONTINUE                        = 100,
  HTTP_STATUS_SWITCHING_PROTOCOLS             = 101,
  HTTP_STATUS_RESPONSE_OK                     = 200,
  HTTP_STATUS_CREATED                         = 201,
  HTTP_STATUS_ACCEPTED                        = 202,
  HTTP_STATUS_NONAUTHORITATIVE                = 203,
  HTTP_STATUS_NO_CONTENT                      = 204,
  HTTP_STATUS_RESET_CONTENT                   = 205,
  HTTP_STATUS_PARTIAL_CONTENT                 = 206,
  HTTP_STATUS_MULTIPLE_CHOICES                = 300,
  HTTP_STATUS_MOVED_PERMANENTLY               = 301,
  HTTP_STATUS_FOUND                           = 302,
  HTTP_STATUS_SEE_OTHER                       = 303,
  HTTP_STATUS_NOT_MODIFIED                    = 304,
  HTTP_STATUS_USEPROXY                        = 305,
  HTTP_STATUS_TEMPORARY_REDIRECT              = 307,
  HTTP_STATUS_BAD_REQUEST                     = 400,
  HTTP_STATUS_UNAUTHORIZED                    = 401,
  HTTP_STATUS_PAYMENT_REQUIRED                = 402,
  HTTP_STATUS_FORBIDDEN                       = 403,
  HTTP_STATUS_NOT_FOUND                       = 404,
  HTTP_STATUS_METHOD_NOT_ALLOWED              = 405,
  HTTP_STATUS_NOT_ACCEPTABLE                  = 406,
  HTTP_STATUS_PROXY_AUTHENTICATION_REQUIRED   = 407,
  HTTP_STATUS_REQUEST_TIMEOUT                 = 408,
  HTTP_STATUS_CONFLICT                        = 409,
  HTTP_STATUS_GONE                            = 410,
  HTTP_STATUS_LENGTH_REQUIRED                 = 411,
  HTTP_STATUS_PRECONDITION_FAILED             = 412,
  HTTP_STATUS_REQUESTENTITYTOOLARGE           = 413,
  HTTP_STATUS_REQUESTURITOOLONG               = 414,
  HTTP_STATUS_UNSUPPORTEDMEDIATYPE            = 415,
  HTTP_STATUS_REQUESTED_RANGE_NOT_SATISFIABLE = 416,
  HTTP_STATUS_EXPECTATION_FAILED              = 417,
  HTTP_STATUS_INTERNAL_SERVER_ERROR           = 500,
  HTTP_STATUS_NOT_IMPLEMENTED                 = 501,
  HTTP_STATUS_BAD_GATEWAY                     = 502,
  HTTP_STATUS_SERVICE_UNAVAILABLE             = 503,
  HTTP_STATUS_GATEWAY_TIMEOUT                 = 504,
  HTTP_STATUS_VERSION_NOT_SUPPORTED           = 505,
} http_status_code_t;

enum HTTPPageType
{
  HTTPPAGE_TYPE_STATIC =0    , // Page is located in ROM or RAM
  HTTPPAGE_TYPE_DYNAMIC      , // Page is dynamically generated
  HTTPPAGE_TYPE_RESOUCE      , // Page is resource struct generated by pyresource
  // Advanced Page
  HTTPPAGE_TYPE_REDIRECT     , // Use HTTP 301 to redirect one page to another
  HTTPPAGE_TYPE_RAW_DYNAMIC  , // Same as DYNAMIC but HTTP headers must be included
  HTTPPAGE_TYPE_RAW_RESOURCE , // Same as RESOURCE but HTTP headers must be included
};


enum HTTPMimeType
{
  HTTP_MIME_TLV = 0                , // "application/x-tlv8"
  HTTP_MIME_APPLE_BINARY_PLIST     , // "application/x-apple-binary-plist"
  HTTP_MIME_APPLE_PROXY_AUTOCONFIG , // "application/x-ns-proxy-autoconfig"
  HTTP_MIME_BINARY_DATA            , // "application/octet-stream"
  HTTP_MIME_JAVASCRIPT             , // "application/javascript"
  HTTP_MIME_JSON                   , // "application/json"
  HTTP_MIME_HAP_PAIRING            , // "application/pairing+tlv8"
  HTTP_MIME_HAP_JSON               , // "application/hap+json"
  HTTP_MIME_HAP_VERIFY             , // "application/hap+verify"
  HTTP_MIME_TEXT_HTML              , // "text/html"
  HTTP_MIME_TEXT_PLAIN             , // "text/plain"
  HTTP_MIME_TEXT_EVENT_STREAM      , // "text/event-stream"
  HTTP_MIME_TEXT_CSS               , // "text/css"
  HTTP_MIME_IMAGE_GIF              , // "image/gif"
  HTTP_MIME_IMAGE_PNG              , // "image/png"
  HTTP_MIME_IMAGE_MICROSOFT        , // "image/vnd.microsoft.icon"
  HTTP_MIME_ALL                    , // "*/*" This must always be the last mimne
};

//--------------------------------------------------------------------+
// HTTP Page
//--------------------------------------------------------------------+
#define HTTPPageRedirect(_url, _redirect)   HTTPPage(_url, _redirect)
#define PAGE404         "/error404.hml"

typedef void (*httppage_generator_t) (const char* url, const char* query, void* http_request);

// This struct's layout must matches with wiced_http_page_t in Featherlib
struct HTTPPage
{
  const char * url;
  const char * _mime_type;
  uint32_t _type;

  // url_content
  union
  {
    struct {
      const void*          featherlib_cb;     // Featherlib internal used only
      httppage_generator_t page_generator;
      void*                this_ptr;
    }_dynamic;

    struct {
      const void* data;
      uint32_t len;
    }_static;
  };

  HTTPPage(const char* page_url, const char* redirect_url);
  HTTPPage(const char* page_url, HTTPMimeType mime_type, const uint8_t* static_page, uint32_t len);
  HTTPPage(const char* page_url, HTTPMimeType mime_type, const char* static_page);
  HTTPPage(const char* page_url, HTTPMimeType mime_type, httppage_generator_t page_generator);
};

// Callback proxy from Featherlib
extern "C"
{
  ATTR_USED int32_t adafruit_httpserver_url_generator_callback(const char* url, const char* query, void* response_stream, void* args[], void* http_data );
}


#endif /* _HTTP_COMMON_H_ */
