#ifndef _CERTIFICATE_H_
#define _CERTIFICATE_H_

#ifdef __cplusplus
extern "C"
{
#endif

const char ca_cert[] =
"-----BEGIN CERTIFICATE-----\r\n"
"MIIEITCCAwmgAwIBAgIJAP54VM63VbasMA0GCSqGSIb3DQEBCwUAMIGmMQswCQYD\r\n"
"VQQGEwJERTEfMB0GA1UECAwWTm9ydGggUmhpbmUtV2VzdHBoYWxpYTESMBAGA1UE\r\n"
"BwwJUGFkZXJib3JuMRkwFwYDVQQKDBBDb21wdXRlciBTY2llbmNlMQwwCgYDVQQL\r\n"
"DANDQ1MxEjAQBgNVBAMMCWxvY2FsaG9zdDElMCMGCSqGSIb3DQEJARYWcXVhbmdo\r\n"
"dXkuY3NlQGdtYWlsLmNvbTAeFw0xNTExMTYxNjAxMTVaFw0xNjExMTUxNjAxMTVa\r\n"
"MIGmMQswCQYDVQQGEwJERTEfMB0GA1UECAwWTm9ydGggUmhpbmUtV2VzdHBoYWxp\r\n"
"YTESMBAGA1UEBwwJUGFkZXJib3JuMRkwFwYDVQQKDBBDb21wdXRlciBTY2llbmNl\r\n"
"MQwwCgYDVQQLDANDQ1MxEjAQBgNVBAMMCWxvY2FsaG9zdDElMCMGCSqGSIb3DQEJ\r\n"
"ARYWcXVhbmdodXkuY3NlQGdtYWlsLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEP\r\n"
"ADCCAQoCggEBAL4XTHQxO45aEjzqnfMKmM0OdCx8SjWIGyygLa45B4RFiF+SgwMJ\r\n"
"Z4qR4Hsr7p9/mmgAT3NSo94a8Uvc5kt6L6mJEh4g2w9H6phzL4HYQ7PJRsXB1X4O\r\n"
"VvlO7tPhacSzZJf5preaO3gdC03ct+Ap5a+fpnajZxuwR26gXQ4FhK2EY3oj34et\r\n"
"ifFbxBDlBB5oosiiNa0tQgolP1Q2Pyvu8KOEmnq0g8v5mPM0nkir96umvXEAPXqv\r\n"
"iyWQl4tKxq5xF3XlCar2nn9LTsHJIvrrmi38u/KlusJHk9i2QKgvJlN6+u5Q0jhD\r\n"
"eheEcGnrRDNlXfyHzAXnGhZhZSL1dlOb5x8CAwEAAaNQME4wHQYDVR0OBBYEFIgW\r\n"
"LuiyfzrqrS8WTV4MCCikbSE5MB8GA1UdIwQYMBaAFIgWLuiyfzrqrS8WTV4MCCik\r\n"
"bSE5MAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAJcBpmTz78ptr16v\r\n"
"zhHjSI6qMkd52NZrm0VR36mvJivASc2wuYodfUVFCJ+2e6IW3KD8AXj9sx1cw9HI\r\n"
"ImCuJnnUA/dHwh+heYbSg7NR7GMqIMHOP4RnfLUrsPdEdTtzxIu0pPOt5n7oSHh2\r\n"
"Dg/D+db1w0AlHRyQjaxqqeIKTdkjgx2d+Ol5DFmDEinJ1ft6kP2IWMiEsx4lydJ5\r\n"
"kwGTmnqMCqhVQdSKuOVjeLN3P03Bd6Z20sAqtxHUBcG9C1Poqw6nZ49w+GPloaRL\r\n"
"mf4Qg/cLjp7M9cI1hxR80+v0pulJ41FUDiCj0jIxglWhkq51oY2DgHNTgA1dH54J\r\n"
"6Ob3t0c=\r\n"
"-----END CERTIFICATE-----\r\n";

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* ifndef _CERTIFICATE_H_ */