#ifndef _RESOURCE_H_
#define _RESOURCE_H_

/* Auto-generated by the pyresource tool. Do not edit */

#include "http_common.h"
#include "d3_min_js.h"
#include "index_html.h"


#endif /* ifndef _RESOURCE_H_ */
