#ifndef _RESOURCE_H_
#define _RESOURCE_H_

/* Auto-generated by pyresource. Do not edit this file. */

#include "http_common.h"
#include "apple_touch_icon_png.h"
#include "browserconfig_xml.h"
#include "crossdomain_xml.h"
#include "err404_html.h"
#include "favicon_ico.h"
#include "index_html.h"
#include "robots_txt.h"
#include "tile_wide_png.h"
#include "tile_png.h"
#include "css_dir_main_css.h"
#include "css_dir_normalize_css.h"
#include "js_dir_main_js.h"
#include "js_dir_plugins_js.h"
#include "js_dir_vendor_dir_jquery_1_12_0_min_js.h"
#include "js_dir_vendor_dir_modernizr_2_8_3_min_js.h"


#endif /* ifndef _RESOURCE_H_ */
