#ifndef _RESOURCE_H_
#define _RESOURCE_H_

/* Auto-generated by pyresource. Do not edit this file. */

#include "http_common.h"
#include "_32px_png.h"
#include "adafruit_logo_png.h"
#include "favicon_ico.h"
#include "file_sprite_png.h"
#include "index_html.h"


/* HTTPPage collect from generated headers

HTTPPage("/32px.png", HTTP_MIME_IMAGE_PNG, &_32px_png),
HTTPPage("/adafruit_logo.png", HTTP_MIME_IMAGE_PNG, &adafruit_logo_png),
HTTPPage("/favicon.ico", HTTP_MIME_IMAGE_MICROSOFT, &favicon_ico),
HTTPPage("/file_sprite.png", HTTP_MIME_IMAGE_PNG, &file_sprite_png),
HTTPPage("/index.html", HTTP_MIME_TEXT_HTML, &index_html),


*/

#endif /* ifndef _RESOURCE_H_ */
